// 90 Graduation Project Ideas with curated technical tags & metadata
const PROJECTS = [
  // 1. الذكاء الاصطناعي والأمن الرقمي (1-20)
  { id: 1, title: 'منصة حماية المستخدم من الاحتيال الرقمي', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'تفحص الرسائل والروابط والصور والإعلانات وتحدد مؤشرات الاحتيال، مع درجة خطورة وشرح سبب التحذير.', tags: ['NLP', 'Phishing Detection', 'Python', 'Web Extension'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 2, title: 'منصة كشف المواقع الاحتيالية', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'تحلل الرابط والنطاق ومحتوى الموقع وخصائصه وتحدد احتمالية كونه موقعاً احتيالياً أو تصيدياً.', tags: ['Cybersecurity', 'Machine Learning', 'FastAPI', 'React'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 3, title: 'نظام ذكي لاكتشاف الاحتيال في الإعلانات الإلكترونية', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يحلل الإعلان والسعر والصور والحساب وطريقة التواصل ويعطي درجة احتمالية الاحتيال مع الأسباب.', tags: ['Computer Vision', 'Data Mining', 'Scraping', 'Python'], level: 'متوسط', team: '3 طلاب' },
  { id: 4, title: 'نظام كشف التلاعب بالمستندات', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يرفع المستخدم صورة أو PDF، والنظام يحلل المستند ويحدد المناطق التي يحتمل تعديلها أو التلاعب بها.', tags: ['OCR', 'Image Forensics', 'Deep Learning', 'PyTorch'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 5, title: 'منصة للتحقق من صحة الصور', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'تكشف القص والدمج والتعديل والتلاعب بالصورة، وتحدد المناطق المشبوهة بدلاً من إعطاء نتيجة عامة فقط.', tags: ['Image Processing', 'CNN', 'Metadata Analysis', 'OpenCV'], level: 'متقدم', team: '3 طلاب' },
  { id: 6, title: 'نظام كشف الفيديوهات Deepfake', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يحلل الفيديو والوجه والحركة والصوت لتحديد احتمالية التلاعب الرقمي بالمقطع.', tags: ['Deepfake Detection', 'Facial Analysis', 'TensorFlow', 'Python'], level: 'متقدم جداً', team: '4 طلاب' },
  { id: 7, title: 'كاشف المحتوى المولد بالذكاء الاصطناعي', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يحلل النصوص والصور والصوت والفيديو ويعطي احتمالية كون المحتوى مولداً أو معدلاً بالذكاء الاصطناعي.', tags: ['LLM Detect', 'Multi-modal AI', 'Transformers', 'FastAPI'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 8, title: 'نظام كشف الصوت المزيف', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يحلل التسجيل الصوتي ويبحث عن خصائص تدل على أن الصوت مولد أو معدل بالذكاء الاصطناعي.', tags: ['Audio Processing', 'Voice Biometrics', 'Librosa', 'ML'], level: 'متقدم', team: '3 طلاب' },
  { id: 9, title: 'نظام ذكي لاكتشاف الحسابات الوهمية', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يحلل نشاط الحساب وسلوكه وعلاقاته ومحتواه لاكتشاف الحسابات التي تظهر عليها خصائص الحسابات المزيفة.', tags: ['Graph Analysis', 'Social Network Analysis', 'Python', 'API'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 10, title: 'منصة اكتشاف الحسابات المنتحلة', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'تقارن الصور والمحتوى والبيانات بين الحسابات لاكتشاف الحسابات التي تنتحل شخصية شخص أو علامة تجارية.', tags: ['Facial Recognition', 'Text Similarity', 'Web Scraping'], level: 'متوسط', team: '3 طلاب' },
  { id: 11, title: 'نظام ذكي لاكتشاف البريد والرسائل الاحتيالية العربية', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يركز على اللغة العربية ويحلل محتوى الرسالة والروابط والمرسل لاكتشاف التصيد والاحتيال.', tags: ['Arabic NLP', 'Spam Filtering', 'HuggingFace', 'Docker'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 12, title: 'نظام ذكي لتحليل المكالمات المشبوهة', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يحول المكالمة إلى نص ثم يحلل محتواها لاكتشاف أساليب الاحتيال مثل طلب البيانات السرية أو رموز التحقق.', tags: ['Speech to Text', 'Whisper', 'NLP Sentiment', 'Python'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 13, title: 'نظام كشف الروابط الخطرة', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يفحص الرابط والوجهة النهائية وخصائص الموقع قبل دخوله، ويعرض مستوى الخطورة للمستخدم.', tags: ['URL Scanner', 'Threat Intelligence', 'REST API', 'Chrome Extension'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 14, title: 'نظام اكتشاف الهجمات داخل الشبكة', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يراقب حركة شبكة تجريبية ويكتشف الأنماط غير الطبيعية التي قد تشير إلى محاولة اختراق أو هجوم.', tags: ['Network IDS', 'Packet Inspection', 'Snort/Zeek', 'Python'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 15, title: 'نظام اكتشاف الهجمات على جهاز الكمبيوتر', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يراقب سلوك العمليات والملفات والاتصالات داخل جهاز تجريبي ويكتشف السلوكيات غير الطبيعية.', tags: ['EDR System', 'Process Monitor', 'Anomaly Detection', 'C++/Python'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 16, title: 'منصة تحليل الملفات الضارة للمؤسسات', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'ترفع المؤسسة الملف إلى بيئة تحليل معزولة، فيتم فحصه وتحليل سلوكه وتصنيفه، مع إمكانية ربط النظام بمؤسسات أخرى لتبادل مؤشرات التهديد دون مشاركة الملفات نفسها.', tags: ['Malware Sandbox', 'Docker Isolation', 'MISP Protocol', 'Threat Intel'], level: 'متقدم جداً', team: '4 طلاب' },
  { id: 17, title: 'نظام ذكي لاكتشاف الملفات الضارة قبل فتحها', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يفحص خصائص الملفات وسلوكها المتوقع ويعطي درجة خطورة قبل السماح للمستخدم بالتعامل معها.', tags: ['Static Analysis', 'PE Header Parsing', 'Machine Learning'], level: 'متوسط', team: '3 طلاب' },
  { id: 18, title: 'منصة Threat Intelligence Cyber للمؤسسات', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'تجمع مؤشرات الهجمات والملفات والنطاقات والعناوين المشبوهة من عدة مصادر وتربطها ببعضها لإظهار التهديدات المشتركة.', tags: ['STIX/TAXII', 'Data Aggregation', 'Dashboard', 'PostgreSQL'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 19, title: 'نظام اكتشاف الأجهزة غير المصرح بها في الشبكة', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يراقب الأجهزة المتصلة ويكتشف الأجهزة الجديدة أو غير المعروفة ويصنف مستوى خطورتها.', tags: ['Network Scanner', 'ARP/DHCP Sniffing', 'IoT Discovery'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 20, title: 'نظام كشف الحسابات المخترقة', category: 'الذكاء الاصطناعي والأمن الرقمي', description: 'يتعلم نمط استخدام الحساب ثم ينبه عند ظهور تسجيل دخول أو نشاط يختلف بشكل كبير عن السلوك المعتاد.', tags: ['User Behavior Analytics', 'Geo-IP', 'Auth Security', 'Node.js'], level: 'متوسط', team: '2-3 طلاب' },

  // 2. الحج والعمرة والسياحة (21-32)
  { id: 21, title: 'منصة ذكية لمساعدة الحاج خطوة بخطوة', category: 'الحج والعمرة والسياحة', description: 'تعرض رحلة الحج كاملة من الاستعداد والسفر وحتى إتمام المناسك، وتوضح للمستخدم ماذا يفعل في كل مرحلة ومتى وأين، مع خرائط وفيديوهات توضيحية.', tags: ['Flutter', 'Interactive Maps', 'Offline Mode', 'Multi-Language'], level: 'متوسط', team: '3-4 طلاب' },
  { id: 22, title: 'مساعد الحج التفاعلي', category: 'الحج والعمرة والسياحة', description: 'يحدد الحاج مرحلته الحالية ويعرض له الخطوة التالية، والتعليمات المتعلقة بها، والموقع على الخريطة، والوقت المتوقع، والفيديو المناسب للشرح.', tags: ['Geofencing', 'Mobile App', 'Smart Assistant', 'Firebase'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 23, title: 'منصة حج مخصصة حسب موقع المستخدم', category: 'الحج والعمرة والسياحة', description: 'تتعرف على موقع الحاج وتخبره بالأماكن القريبة منه والخطوة التالية في رحلته، مع التنبيهات عند الانتقال بين مراحل المناسك.', tags: ['GPS Services', 'Real-time Alerts', 'Location Aware', 'Maps API'], level: 'متوسط', team: '3 طلاب' },
  { id: 24, title: 'دليل ذكي للحج متعدد اللغات', category: 'الحج والعمرة والسياحة', description: 'يقدم شرح المناسك والأماكن والتنبيهات بعدة لغات، مع إمكانية اختيار لغة المستخدم ومستوى التفاصيل الذي يريده.', tags: ['Localization (i18n)', 'Text-to-Speech', 'React Native', 'Audio Guide'], level: 'سهل - متوسط', team: '2-3 طلاب' },
  { id: 25, title: 'منصة سياحية ذكية للزوار في السعودية', category: 'الحج والعمرة والسياحة', description: 'يدخل المستخدم مدينته أو موقعه واهتماماته، فتحولها المنصة إلى برنامج سياحي يومي يشمل الأماكن والأنشطة والمطاعم.', tags: ['Recommendation Engine', 'Tourism API', 'Next.js', 'PostgreSQL'], level: 'متوسط', team: '3 طلاب' },
  { id: 26, title: 'نظام سياحي يتكيف مع بلد المستخدم', category: 'الحج والعمرة والسياحة', description: 'يحدد المستخدم بلده، ثم تقترح المنصة أماكن سياحية ومطاعم وتجارب تناسب ثقافته واهتماماته وميزانيته.', tags: ['Personalization', 'Cultural AI', 'Tailwind', 'Python/Django'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 27, title: 'منصة ماذا يوجد حولي؟ للسياح', category: 'الحج والعمرة والسياحة', description: 'تعرض الأماكن السياحية والمطاعم والمقاهي والفعاليات والخدمات القريبة من المستخدم، مع ترتيبها حسب اهتماماته.', tags: ['Geolocation', 'Places API', 'Mobile PWA', 'Filtering'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 28, title: 'مخطط رحلات سياحية ذكي', category: 'الحج والعمرة والسياحة', description: 'يحدد المستخدم المدينة وعدد الأيام والميزانية، والنظام يبني له جدولاً متكاملاً للأماكن والمطاعم والأنشطة وأوقات الزيارة.', tags: ['Itinerary Planner', 'Optimization Algorithm', 'React', 'FastAPI'], level: 'متوسط', team: '3 طلاب' },
  { id: 29, title: 'منصة مقارنة التجارب السياحية', category: 'الحج والعمرة والسياحة', description: 'تقارن بين الأنشطة والأماكن من حيث السعر والتقييم والمسافة والمدة ونوع التجربة وتوصي بما يناسب المستخدم.', tags: ['Comparison Engine', 'Review Analysis', 'Web App', 'SQL'], level: 'سهل - متوسط', team: '2-3 طلاب' },
  { id: 30, title: 'دليل المطاعم الذكي للسياح', category: 'الحج والعمرة والسياحة', description: 'يحدد المستخدم بلده أو نوع الطعام الذي يفضله، والمنصة تقترح مطاعم قريبة تقدم أطعمة مشابهة لما اعتاد عليه.', tags: ['Food Recommendation', 'Dietary Filters', 'Google Maps API'], level: 'سهل - متوسط', team: '2 طلاب' },
  { id: 31, title: 'منصة اكتشاف الأماكن السياحية الأقل ازدحاماً', category: 'الحج والعمرة والسياحة', description: 'تستخدم بيانات الزيارات والأوقات لتقترح على السائح أوقاتاً وأماكن بديلة أقل ازدحاماً.', tags: ['Crowd Analytics', 'Time-series Forecasting', 'Data Visuals'], level: 'متقدم', team: '3 طلاب' },
  { id: 32, title: 'نظام ذكي لإدارة تجربة الزائر', category: 'الحج والعمرة والسياحة', description: 'يجمع خط سير السائح وحجوزاته وأماكنه المفضلة ويقدم له تنبيهات واقتراحات أثناء الرحلة.', tags: ['Booking Hub', 'Push Notifications', 'CRM/Visitor Portal'], level: 'متوسط', team: '3 طلاب' },

  // 3. المفقودون وإدارة الأحداث والطوارئ (33-40)
  { id: 33, title: 'منصة ذكية للعثور على المفقودين', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'تسجل بيانات الشخص المفقود وصورته وموقع آخر ظهور، وتساعد في مطابقة البلاغات والصور والمعلومات للوصول إلى تطابقات محتملة.', tags: ['Facial Match', 'Case Management', 'Geomapping', 'Cloud Storage'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 34, title: 'نظام مطابقة صور الأشخاص المفقودين', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'يقارن الصور المرفوعة مع الصور المسجلة في النظام باستخدام تقنيات التعرف على الصور، مع مراعاة الخصوصية والصلاحيات.', tags: ['Face Recognition', 'Deep Learning', 'RBAC', 'Python/PyTorch'], level: 'متقدم', team: '3 طلاب' },
  { id: 35, title: 'منصة إدارة بلاغات المفقودين', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'تجمع البلاغات من عدة جهات، وتمنع تكرار البلاغات وتربط المعلومات المتشابهة وتعرض آخر المواقع المعروفة على الخريطة.', tags: ['Deduplication', 'Incident Reporting', 'Interactive Map', 'GIS'], level: 'متوسط', team: '3 طلاب' },
  { id: 36, title: 'نظام إدارة الأحداث والفعاليات', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'ينظم الحدث من التسجيل والتذاكر والدخول وحتى إدارة الحشود والمرافق والبلاغات أثناء الفعالية.', tags: ['QR Ticketing', 'Access Control', 'Live Dashboard', 'Node.js'], level: 'متوسط', team: '3-4 طلاب' },
  { id: 37, title: 'نظام ذكي لإدارة الحشود', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'يحلل بيانات الحضور أو صور الكاميرات في بيئة تجريبية لتقدير الكثافة واكتشاف الازدحام غير الطبيعي.', tags: ['Crowd Density Estimation', 'YOLO/Vision', 'Heatmaps', 'Alerts'], level: 'متقدم جداً', team: '4 طلاب' },
  { id: 38, title: 'منصة إدارة الطوارئ', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'تجمع البلاغات والمواقع والموارد والفرق الميدانية وتحدد أولوية البلاغات وتقترح توزيع فرق الاستجابة.', tags: ['Emergency Dispatch', 'Priority Queuing', 'Field Ops App', 'WebSockets'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 39, title: 'نظام توجيه الزوار أثناء الطوارئ', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'يحدد مناطق الخطر ومخارج الطوارئ ويقترح للمستخدم أقرب مسار آمن بناءً على حالة المكان.', tags: ['Indoor Navigation', 'Pathfinding (A*)', 'Safety Routing'], level: 'متقدم', team: '3 طلاب' },
  { id: 40, title: 'نظام إدارة الفعاليات مع خريطة تفاعلية', category: 'المفقودون وإدارة الأحداث والطوارئ', description: 'يعرض مواقع المداخل والمخارج والمطاعم والخدمات ودورات المياه ومناطق الفعاليات مع إمكانية توجيه الزائر.', tags: ['Interactive Floorplan', 'Mapbox/Leaflet', 'Event Schedule'], level: 'متوسط', team: '2-3 طلاب' },

  // 4. الزراعة والبيئة (41-50)
  { id: 41, title: 'نظام ذكي لتحليل التربة والري', category: 'الزراعة والبيئة', description: 'يجمع بيانات رطوبة التربة ودرجة الحرارة وغيرها ويحدد احتياج النبات للمياه ويقترح كمية الري المناسبة.', tags: ['IoT Sensors', 'Soil Moisture', 'ESP32/Arduino', 'Telemetry'], level: 'متوسط', team: '3 طلاب' },
  { id: 42, title: 'نظام سقي تلقائي ذكي', category: 'الزراعة والبيئة', description: 'يعتمد على رطوبة التربة والحرارة وحالة النبات لتحديد وقت تشغيل الري وإيقافه بدلاً من الري وفق جدول ثابت.', tags: ['Smart Irrigation', 'Actuators & Relays', 'Mobile App', 'MQTT'], level: 'متوسط', team: '3 طلاب' },
  { id: 43, title: 'منصة ذكية لإدارة المزرعة', category: 'الزراعة والبيئة', description: 'تجمع بيانات التربة والري والطقس والنباتات وتعرض حالة المزرعة وتقدم توصيات بناءً على البيانات.', tags: ['Farm Dashboard', 'Weather API', 'Analytics', 'Fullstack'], level: 'متوسط', team: '3-4 طلاب' },
  { id: 44, title: 'نظام اكتشاف أمراض النباتات من الصور', category: 'الزراعة والبيئة', description: 'يصور المستخدم الورقة أو الثمرة، والنظام يحلل الصورة ويحدد احتمالات المرض مع معلومات أولية عنه.', tags: ['Plant Pathology', 'Mobile Vision', 'CNN Classifier', 'TFLite'], level: 'متوسط - متقدم', team: '3 طلاب' },
  { id: 45, title: 'نظام تحديد احتياج النبات للمياه', category: 'الزراعة والبيئة', description: 'يحلل نوع النبات وحالة التربة ودرجة الحرارة والطقس ليحدد متى يحتاج النبات إلى الري.', tags: ['Crop Water Model', 'Evapotranspiration', 'Data Model'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 46, title: 'منصة التنبؤ بإنتاج المحاصيل', category: 'الزراعة والبيئة', description: 'تستخدم بيانات الزراعة السابقة والتربة والطقس لتقدير الإنتاج المتوقع ومساعدة المزارع في التخطيط.', tags: ['Yield Prediction', 'Regression Models', 'Statistical Charts'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 47, title: 'نظام كشف تسرب المياه في أنظمة الري', category: 'الزراعة والبيئة', description: 'يحلل تدفق المياه وقراءات الحساسات ويكتشف الاستهلاك غير الطبيعي الذي قد يدل على تسرب.', tags: ['Flow Sensors', 'Leak Detection', 'Anomaly Alerting', 'IoT'], level: 'متوسط', team: '3 طلاب' },
  { id: 48, title: 'نظام ذكي لمراقبة جودة الهواء', category: 'الزراعة والبيئة', description: 'يجمع بيانات جودة الهواء ويعرضها على خريطة ويتنبأ بالتغيرات غير الطبيعية.', tags: ['Air Quality Index (AQI)', 'Gas Sensors', 'Live Heatmap'], level: 'متوسط', team: '3 طلاب' },
  { id: 49, title: 'نظام ذكي لإدارة النفايات', category: 'الزراعة والبيئة', description: 'يتابع مستوى امتلاء الحاويات ويتوقع موعد امتلائها ويقترح أفضل مسارات الجمع.', tags: ['Smart Waste', 'Ultrasonic Sensors', 'Route Optimization'], level: 'متوسط', team: '3 طلاب' },
  { id: 50, title: 'نظام فرز النفايات باستخدام الصور', category: 'الزراعة والبيئة', description: 'يصور المستخدم النفاية، والنظام يحدد نوعها ويقترح طريقة التخلص أو إعادة التدوير المناسبة.', tags: ['Waste Classification', 'Computer Vision', 'Eco Guidelines'], level: 'متوسط', team: '2-3 طلاب' },

  // 5. التجارة الإلكترونية والمزادات (51-60)
  { id: 51, title: 'متجر إلكتروني ذكي', category: 'التجارة الإلكترونية والمزادات', description: 'متجر تقليدي لكن مع نظام توصية يتعلم من سلوك المستخدم ويقترح المنتجات المناسبة له بدلاً من عرض المنتجات بشكل عشوائي.', tags: ['E-Commerce', 'Recommendation System', 'Stripe/Payment', 'React'], level: 'متوسط', team: '3 طلاب' },
  { id: 52, title: 'منصة مزاد إلكتروني ذكية', category: 'التجارة الإلكترونية والمزادات', description: 'تسمح بإنشاء المزادات والمزايدة عليها، مع نظام يمنع المزايدات المشبوهة ويكتشف السلوك غير الطبيعي للمستخدمين.', tags: ['Live Bidding', 'WebSockets', 'Fraud Prevention', 'Node.js'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 53, title: 'مزاد ذكي يعتمد على تحليل الأسعار', category: 'التجارة الإلكترونية والمزادات', description: 'يحلل أسعار المنتجات والمزايدات السابقة ويعرض للمستخدم السعر المتوقع أو نطاق السعر المناسب للمزايدة.', tags: ['Price Estimation', 'Market Analysis', 'Predictive Model'], level: 'متوسط', team: '3 طلاب' },
  { id: 54, title: 'منصة مزاد للمنتجات المستعملة', category: 'التجارة الإلكترونية والمزادات', description: 'تسمح للمستخدم بتصوير المنتج وإضافته للمزاد، مع تحليل الصور ووصف الحالة واقتراح سعر ابتدائي.', tags: ['C2C Marketplace', 'Image Assessment', 'Escrow System'], level: 'متوسط', team: '3 طلاب' },
  { id: 55, title: 'نظام كشف الاحتيال في المزادات', category: 'التجارة الإلكترونية والمزادات', description: 'يراقب أنماط المزايدة ويكتشف الحسابات التي تتفق أو تتلاعب بالمزايدات بشكل غير طبيعي.', tags: ['Shill Bidding Detection', 'Pattern Recognition', 'Fraud Graph'], level: 'متقدم', team: '3 طلاب' },
  { id: 56, title: 'متجر إلكتروني مع نظام اكتشاف المنتجات المقلدة', category: 'التجارة الإلكترونية والمزادات', description: 'يفحص بيانات المنتج وصوره ورقمه التسلسلي أو QR ويعرض درجة الثقة في المنتج.', tags: ['Anti-Counterfeit', 'QR/Barcode Verification', 'Trust Score'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 57, title: 'منصة اكتشاف الأسعار غير الطبيعية', category: 'التجارة الإلكترونية والمزادات', description: 'تجمع تاريخ أسعار المنتج وتحدد ما إذا كان السعر الحالي مبالغاً فيه أو منخفضاً بشكل غير معتاد.', tags: ['Price History Tracker', 'Web Scraping', 'Dynamic Pricing'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 58, title: 'نظام اكتشاف الخصومات الوهمية', category: 'التجارة الإلكترونية والمزادات', description: 'يحلل تاريخ السعر ويحدد ما إذا كان الخصم حقيقياً أم تم رفع السعر قبل الإعلان عن التخفيض.', tags: ['Fake Deal Detector', 'Browser Extension', 'Price Analysis'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 59, title: 'نظام تحليل تقييمات المنتجات', category: 'التجارة الإلكترونية والمزادات', description: 'يحلل مراجعات العملاء ويكتشف التقييمات المزيفة ويستخرج أكثر الأشياء التي يشتكي أو يمدحها العملاء.', tags: ['Review Sentiment Analysis', 'Fake Review Detector', 'Aspect Mining'], level: 'متوسط', team: '3 طلاب' },
  { id: 60, title: 'منصة توصية ذكية للمنتجات', category: 'التجارة الإلكترونية والمزادات', description: 'تتعلم من عمليات البحث والتصفح والشراء وتقدم لكل مستخدم منتجات مناسبة لسلوكه واهتماماته.', tags: ['Collaborative Filtering', 'Matrix Factorization', 'AI Shopping'], level: 'متقدم', team: '3 طلاب' },

  // 6. السيارات والنقل (61-68)
  { id: 61, title: 'نظام اكتشاف النعاس أثناء القيادة', category: 'السيارات والنقل', description: 'يستخدم كاميرا الهاتف لمراقبة العين والوجه ويصدر تنبيهاً عند اكتشاف علامات النعاس.', tags: ['Driver Drowsiness', 'Eye Aspect Ratio (EAR)', 'OpenCV', 'Mobile'], level: 'متوسط - متقدم', team: '3 طلاب' },
  { id: 62, title: 'نظام تشخيص أعطال السيارة من الصوت', category: 'السيارات والنقل', description: 'يسجل المستخدم صوت المحرك، ويحلله النظام ويقارنه بأنماط صوتية مرتبطة بأعطال مختلفة.', tags: ['Acoustic Diagnostics', 'Audio Classification', 'Spectrograms'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 63, title: 'نظام ذكي لاكتشاف الحفر في الطرق', category: 'السيارات والنقل', description: 'يحلل الصور أو الفيديو من كاميرا الهاتف ويكتشف الحفر والتشققات ويحدد موقعها على الخريطة.', tags: ['Pothole Detection', 'YOLO', 'GIS Mapping', 'Crowdsourced Road Data'], level: 'متوسط - متقدم', team: '3 طلاب' },
  { id: 64, title: 'نظام تحليل استهلاك الوقود', category: 'السيارات والنقل', description: 'يحلل الرحلات وسلوك القيادة ويحدد أسباب زيادة استهلاك الوقود ويقدم توصيات لتحسينه.', tags: ['OBD-II Telematics', 'Eco-Driving Metrics', 'Data Analytics'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 65, title: 'منصة ذكية لإدارة الأسطول', category: 'السيارات والنقل', description: 'تتابع المركبات والصيانة واستهلاك الوقود وسلوك السائقين وتكتشف الحالات غير الطبيعية.', tags: ['Fleet Management', 'Live GPS Tracking', 'Maintenance Alerts'], level: 'متوسط - متقدم', team: '3-4 طلاب' },
  { id: 66, title: 'نظام تحديد أفضل مسار للتوصيل', category: 'السيارات والنقل', description: 'يرتب عدة طلبات ومواقع ويحسب المسار الأفضل لتقليل المسافة والوقت مع مراعاة أولوية الطلبات.', tags: ['Traveling Salesperson (TSP)', 'VRP Optimization', 'Routing Engine'], level: 'متقدم', team: '3 طلاب' },
  { id: 67, title: 'نظام التنبؤ بأعطال السيارات', category: 'السيارات والنقل', description: 'يستخدم سجل الصيانة وبيانات السيارة للتنبؤ بالأعطال المحتملة قبل حدوثها.', tags: ['Predictive Maintenance', 'Failure Forecasting', 'Machine Learning'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 68, title: 'منصة ذكية لإدارة مواقف السيارات', category: 'السيارات والنقل', description: 'تعرض المواقف المتاحة وتتوقع المواقف التي ستصبح شاغرة وتساعد المستخدم في الوصول إليها.', tags: ['Smart Parking', 'Camera Occupancy', 'Navigation Link'], level: 'متوسط', team: '3 طلاب' },

  // 7. أنظمة الأعمال والخدمات (69-79)
  { id: 69, title: 'منصة تحليل شكاوى العملاء', category: 'أنظمة الأعمال والخدمات', description: 'تحلل آلاف الشكاوى وتجمع المتشابه منها وتحدد أكثر المشاكل تكراراً وأولويتها.', tags: ['NLP Clustering', 'Customer Feedback', 'Ticket Prioritization'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 70, title: 'نظام ذكي لإدارة الممتلكات', category: 'أنظمة الأعمال والخدمات', description: 'يسجل الأجهزة والممتلكات والفواتير والضمانات والصيانة ويوفر تنبيهات قبل انتهاء الضمان.', tags: ['Asset Management', 'Warranty Tracker', 'Automated Notifications'], level: 'سهل - متوسط', team: '2-3 طلاب' },
  { id: 71, title: 'نظام تحليل الفواتير بالذكاء الاصطناعي', category: 'أنظمة الأعمال والخدمات', description: 'يصور المستخدم الفاتورة، فيستخرج المنتجات والأسعار والضريبة والإجمالي ويصنف المصروفات تلقائياً.', tags: ['Invoice OCR', 'Information Extraction', 'Expense Categorization'], level: 'متوسط - متقدم', team: '3 طلاب' },
  { id: 72, title: 'منصة ذكية لإدارة الضمانات', category: 'أنظمة الأعمال والخدمات', description: 'تستخرج بيانات المنتج من الفاتورة وتربطها بتاريخ انتهاء الضمان وترسل تنبيهات للمستخدم.', tags: ['Document AI', 'Warranty Expiry Alerts', 'Customer App'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 73, title: 'نظام ذكي لمراقبة المخزون بالكاميرا', category: 'أنظمة الأعمال والخدمات', description: 'يصور الموظف الرفوف، ويتعرف النظام على المنتجات والكميات ويكتشف النقص.', tags: ['Shelf Monitoring', 'Object Detection', 'Retail Computer Vision'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 74, title: 'نظام ذكي لاكتشاف المنتجات المعيبة', category: 'أنظمة الأعمال والخدمات', description: 'يفحص المنتجات بالكاميرا ويكتشف الخدوش والتشققات والاختلافات الظاهرية قبل بيعها.', tags: ['Quality Assurance', 'Defect Inspection', 'Industrial Vision'], level: 'متقدم', team: '3 طلاب' },
  { id: 75, title: 'نظام تنبؤ بالطلب على المنتجات', category: 'أنظمة الأعمال والخدمات', description: 'يحلل المبيعات السابقة ويتنبأ بالطلب المستقبلي لمساعدة المتجر على تحديد كمية المخزون.', tags: ['Demand Forecasting', 'Time-Series ARIMA/Prophet', 'ERP Connector'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 76, title: 'نظام ذكي لاكتشاف المشكلات المتكررة في المنتجات', category: 'أنظمة الأعمال والخدمات', description: 'يحلل تقييمات العملاء والشكاوى ويحدد العيوب التي تتكرر في منتج معين.', tags: ['Root Cause Analysis', 'Text Analytics', 'Product Quality'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 77, title: 'منصة ذكية لإدارة الطوابير', category: 'أنظمة الأعمال والخدمات', description: 'تحسب وقت الانتظار المتوقع بناءً على البيانات السابقة وتتيح للمستخدم متابعة دوره عن بعد.', tags: ['Virtual Queuing', 'Wait Time Estimation', 'SMS/WhatsApp Alerts'], level: 'متوسط', team: '3 طلاب' },
  { id: 78, title: 'نظام ذكي لاكتشاف هدر الكهرباء', category: 'أنظمة الأعمال والخدمات', description: 'يحلل استهلاك الكهرباء ويحدد الأنماط غير الطبيعية وأوقات الهدر ويقترح طرقاً لتقليل الاستهلاك.', tags: ['Smart Meter Analytics', 'Energy Waste Detection', 'Cost Optimization'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 79, title: 'نظام ذكي لاكتشاف تسرب المياه', category: 'أنظمة الأعمال والخدمات', description: 'يحلل نمط استهلاك المياه ويكتشف التغيرات غير الطبيعية التي قد تشير إلى وجود تسرب.', tags: ['Water Consumption Tracking', 'Leak Alert Engine', 'Dashboard'], level: 'متوسط', team: '2-3 طلاب' },

  // 8. أفكار تقنية مختلفة وقوية (80-90)
  { id: 80, title: 'منصة بحث ذكية داخل الملفات', category: 'أفكار تقنية مختلفة وقوية', description: 'يرفع المستخدم ملفات PDF وWord ويسأل عنها باللغة الطبيعية، ويحصل على الإجابة مع تحديد مصدر المعلومة داخل الملف.', tags: ['RAG Architecture', 'Vector DB (Pinecone/Chroma)', 'LangChain', 'PDF Engine'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 81, title: 'منصة مقارنة المستندات الذكية', category: 'أفكار تقنية مختلفة وقوية', description: 'ترفع نسختين من مستند، والنظام يحدد التغييرات والإضافات والحذف بينهما بطريقة واضحة.', tags: ['Semantic Diff', 'Document Comparison', 'Visual Annotations'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 82, title: 'نظام تحويل اللغة الطبيعية إلى SQL', category: 'أفكار تقنية مختلفة وقوية', description: 'يكتب المستخدم سؤاله بلغة طبيعية، والنظام يحوله إلى استعلام قاعدة بيانات ويعرض النتيجة.', tags: ['Text-to-SQL', 'Database Schema Linking', 'LLM Agents'], level: 'متقدم', team: '3 طلاب' },
  { id: 83, title: 'نظام ذكي لاكتشاف الأخطاء في البيانات', category: 'أفكار تقنية مختلفة وقوية', description: 'يفحص CSV/Excel ويكتشف القيم المفقودة والتكرار والقيم الشاذة والتناقضات.', tags: ['Data Quality Profiler', 'Outlier Detection', 'Automated Audit'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 84, title: 'منصة تنظيف البيانات تلقائياً', category: 'أفكار تقنية مختلفة وقوية', description: 'ترفع Dataset، والنظام يكتشف مشاكل البيانات ويقترح عمليات التنظيف والتصحيح.', tags: ['Auto-Data Cleaning', 'Pandas/Polars', 'Interactive Pipeline'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 85, title: 'نظام تحليل سجلات الخوادم بالذكاء الاصطناعي', category: 'أفكار تقنية مختلفة وقوية', description: 'يحلل Logs ويكتشف الأخطاء والأنماط غير الطبيعية ويرتب المشاكل حسب خطورتها.', tags: ['Log Anomaly Detection', 'Elasticsearch/OpenSearch', 'DevOps AI'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 86, title: 'نظام التنبؤ بانقطاع الخدمات', category: 'أفكار تقنية مختلفة وقوية', description: 'يحلل أداء الخوادم والشبكات ويحدد مؤشرات قد تسبق حدوث العطل.', tags: ['Predictive SRE', 'Server Health Telemetry', 'Alerting System'], level: 'متقدم', team: '3-4 طلاب' },
  { id: 87, title: 'منصة ذكية لاختبار المواقع', category: 'أفكار تقنية مختلفة وقوية', description: 'تفحص الموقع وتكتشف الروابط المعطلة ومشاكل الواجهة وبعض مشاكل Accessibility وتجربة المستخدم.', tags: ['Automated Testing', 'Lighthouse Audit', 'Accessibility (a11y)'], level: 'متوسط', team: '2-3 طلاب' },
  { id: 88, title: 'نظام يحول المتطلبات البرمجية إلى Test Cases', category: 'أفكار تقنية مختلفة وقوية', description: 'يأخذ وثيقة المتطلبات ويولد حالات اختبار وسيناريوهات وحالات Edge Cases.', tags: ['QA Automation', 'Requirements Parsing', 'Test Generator'], level: 'متوسط - متقدم', team: '2-3 طلاب' },
  { id: 89, title: 'نظام اكتشاف التناقضات في متطلبات البرمجيات', category: 'أفكار تقنية مختلفة وقوية', description: 'يحلل وثيقة المتطلبات ويكتشف المتطلبات المتعارضة أو الناقصة أو المتكررة.', tags: ['Software Engineering AI', 'Conflict Resolution', 'Spec Validator'], level: 'متقدم', team: '3 طلاب' },
  { id: 90, title: 'منصة ذكية لتحليل المخاطر الرقمية', category: 'أفكار تقنية مختلفة وقوية', description: 'تحلل إعدادات الحسابات والأجهزة والسلوكيات الرقمية وتحدد المخاطر الأمنية وتقدم توصيات للتحسين.', tags: ['Cyber Risk Score', 'Security Audit', 'Privacy Recommendations'], level: 'متوسط', team: '3 طلاب' }
];

// Provide access in browser & Node.js environments
if (typeof window !== 'undefined') {
  window.PROJECTS = PROJECTS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROJECTS };
}
